# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 554b445e0a82aa4699d28e26353454572338d80c67da043694d0cbe84e87c06690227154ff74b154360931ab4278b31eb0e2ba06a7b28c9c7ea7c3717c87e8ef

test:
  secret_key_base: a5cd90fb3bfa208aefc0bf5c0c9c3d6b9a0a056a9c4dd0c658ee47fd52f63b54c461be86af4d9dffdbff817f873c849660953cdd1e3ad86c6e50d9fc05ff4c8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
